name: Auto Merge on PR Approval

on:
  pull_request:
    types:
      - closed

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto merge on PR approval
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Make sure you have the latest changes
        git pull origin main
        
        # Merge the PR branch into main
        git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }}
        
        # Push the changes back to the repository
        git push origin main
